[Liabilities]
"Credit Card:CMB5434" = [
    [
        "招商银行信用卡(5434)",
        "微信-招商银行信用卡",
        "招商银行信用卡",
    ],
    [
        '招商.*信用卡还款',
    ],
]
"Credit Card:BOC9032" = [
    [
        "中国银行信用卡(9032)",
        "中国银行信用卡",
        "微信-中国银行信用卡",
    ],
    [
        '中国银行.*信用卡.*还款',
    ],
]
"Huabei" = [["江苏银行信用购", "江苏银行信用购(原花呗)", "花呗", "江苏银行信用购分期(3期)"], ['还款-花呗']]
"Baitiao" = [["京东白条"], ['白条.*还款']]
[Assets]
"Current Assets:Checkings Account:SPD9543" = [["6257****9543"], []]
"Current Assets:Checkings Account:BOC4529" = [
    [
        "中国银行储蓄卡",
        "中国银行",
        "中国银行储蓄卡(4529)",
        "中国银行上海分行",
    ],
    [
    ],
]
"Current Assets:Checkings Account:ICBC5489" = [
    [
        "中国工商银行储蓄卡(5489)",
        "工商银行储蓄卡(5489)",
        "工商银行储蓄卡",
        "微信-工商银行储蓄卡",
        "中国工商银行",
        "6217****5489",
    ],
    [
        "普通充值",
    ],
]
"Current Assets:Cash in Wallet" = [[], ['ATM取款', '卡存', '卡取']]
"Current Assets:Checkings Account:Yu'E Bao" = [
    [
        "余额宝",
    ],
    [
        '余额宝-自动转入',
        '余额宝-单次转入',
        '余额宝-转出',
    ],
]
"Current Assets:Checkings Account:JD Jinku" = [["京东小金库", "小金库零用钱"], ["京东小金库"]]
"Current Assets:Checkings Account:JD Yu'E" = [["钱包余额"], ['京东钱包余额']]
"Current Assets:Checkings Account:Alipay Balance" = [["账户余额", "余额"], []]
"Current Assets:Checkings Account:Wexin Pay" = [
    [
        "零钱",
        "微信支付",
        "微信零钱",
    ],
    [
        '零钱充值',

    ],
]
"Current Assets:Checkings Account:LingQianTong" = [[], ['零钱通']]


[Income]
"Interest Income:Checking Interest" = ['余额宝-.*-收益发放', '利息', '薪金溢']
"Other Income" = [
    '提现',
    '收钱码收款',
    '支付宝五福',
    '羊毛星球',
    '返现',
    '理赔-运费险',
    '运费已退回',
    '补运费',
    '摇摇乐',
    '微信支付红包',
    '红包奖励',
    '补贴红包',
    '体.*彩',
]
"Gifts Received" = ['转账', '收到普通红包', '微信红包']
"Bonus" = ['分红']
"Salary" = ['工资']

[Expenses]
"Utilities:Gas" = ['燃气费']
"Utilities:Water" = ['水费']
"Utilities:Electric" = ['电费']
"Computer" = ['电脑', '处理器', '手写笔', 'ipad']
"Dining" = [
    '盒马',
    '涓选',
    '饿了么',
    '叮咚买菜',
    '餐饮',
    '美团',
    '食品酒饮',
    '京东到家',
    '汉堡王',
    '堂食',
    '肯德基',
    '麦当劳',
    '手工面',
    '肉夹馍',
    '大厨房',
    '老乡鸡',
    '农夫山泉',
    '大排档',
    '面馆',
    '拉面',
    '鸡排',
    '羊锅',
    '牛肉',
    '黄牛馆',
    '汤包',
    '国铁吉讯',
    '汤粉',
    '米粉',
    '麻辣烫',
    '餐厅',
    '火锅',
    '馄饨',
    '小吃',
    '骨汤',
    '煎包',
    '黄焖鸡',
    '摊摊面',
    '早餐',
    '腊汁肉',
    '泡馍',
    '包子',
    '肥牛',
    '牛奶',
]
"Auto:Fuel" = ['团油平台', '加油', '石油', '充电服务']
"Auto:Repair and Maintenance" = [
    '汽车钥匙',
    '机动车检测',
    '途虎养车',
    '补胎',
    '汽车贴膜',
    '汽车轮胎',
    '汽车清洗剂',
    '汽车坐垫',
]
"Auto:Parking" = ['停车', '停车场充值', '科拓']
"Auto:Fees" = ['ETC', '高速']
"Insurance:Auto Insurance" = ['车险', '中国人保']
"Public Transportation" = [
    '打车',
    '地铁',
    '公交',
    '单车',
    '租车',
    '骑行卡',
    '滴滴',
    '包车',
    '火车票',
    '货拉拉',
    '12306',
    '巴士',
    '哈啰出行',
    '高铁',
    '交通卡',
    '智能交通',
    '城市通',
]
"Delivery" = ['运费', '丰巢']
"Medical Expenses" = ['医院', '医疗健康', '医疗保健', '医药']
"Online Services" = ['vip', 'PLUS京典年卡', 'PLUS会员', '京东会员', '腾讯云']
"Entertainment:Music/Movies" = ['猫眼', 'K歌']
"Entertainment:Travel" = ['酒店', '机票', '旅行', '观光车', '机场']
"Entertainment:Recreation" = ['青少年活动中心', '跳绳', '体育']
"Clothes" = ['迪卡侬', '优衣库', '特步', '服饰', '鞋服箱包', '跑鞋', '男装']
"Personal Care" = ['美妆个护', '美容美发', '形象设计']
"Books" = ['图书文娱', '作品', '套装', '新华书店', '当当']
"Hobbies" = ['耳机', '羽毛球']
"HouseHold" = [
    '电动.*车',
    '电.*锅',
    '洗衣机',
    '电池',
    '电热饭盒',
    '冰箱',
    '电视机',
    '晾衣杆',
    '扫地机器人',
    '空调',
    '电视',
    '风扇',
    'LED.*灯',
    '家居家装',
    '油烟机',
    '电熨斗',
    "电磁炉",
]
"Phone" = ['话费', '中国电信', '中国移动', '通讯', '联合网络', '通信']
"Groceries" = ['商场', '超市', '水果', '糕点', '日用百货', '环保袋', '烟酒', '蛋糕', '便利店', '炒货']
"Gifts" = [
    '亲情卡',
    'Transfer',
    '发普通红包',
    '转账',
    '微信红包',
    '帮好友.*还白条',
    '群收款',
    'AA收款',
    '亲友代付',
]
"Miscellaneous" = [
    '商业服务',
    '电子书籍',
    '文化休闲',
    '生活服务',
    '教育培训',
    '扫二维码付款',
    '面对面收款',
    '其他',
]
