[jd]
"收/付款方式" = ['微信支付']

[wxpay]
"交易对方" = ['拼多多', '京东']
"商品" = ['京东']

[icbc]
"交易场所" = ["支付宝", "京东支付", "财付通", "微信支付"]
"对方户名" = ["京东", "基金赎回", "支付宝", "蚂蚁"]
"摘要" = ["余额宝转出到卡", "余额宝提现", "开户"]

[alipay]
"交易状态" = ["冻结成功", "已关闭"]
"商品说明" = ["医保支付", "油卡支付"]
"收/付款方式" = ["他人代付账户", "^红包$", "基金份额红包", "&余额宝"]
